# Generated by Django 4.0.5 on 2022-07-06 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline_companies',
            old_name='User_ID',
            new_name='User_Id',
        ),
        migrations.RemoveField(
            model_name='adminstrators',
            name='createdTime',
        ),
        migrations.RemoveField(
            model_name='airline_companies',
            name='createdTime',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='createdTime',
        ),
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='adminstrators',
            name='First_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adminstrators',
            name='Last_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='airline_companies',
            name='Name',
            field=models.CharField(max_length=52, unique=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='Name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='Address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customers',
            name='Credit_Card_no',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='First_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customers',
            name='Last_Name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customers',
            name='Phone_No',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='Customer_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.customers'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='Flight_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.flights'),
        ),
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='Id',
            field=models.BigAutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=models.CharField(max_length=52),
        ),
        migrations.AlterField(
            model_name='users',
            name='Username',
            field=models.CharField(max_length=52, unique=True),
        ),
    ]
