# Generated by Django 4.0.5 on 2022-07-09 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_user_id_airline_companies_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminstrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='AirlineCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52, unique=True)),
            ],
            options={
                'db_table': 'airline_companies',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
            ],
            options={
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=64)),
                ('phone_no', models.CharField(max_length=32, unique=True)),
                ('credit_card_no', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('landing_time', models.DateTimeField()),
                ('remaining_tickets', models.IntegerField()),
                ('airline_company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.airlinecompany')),
                ('destination_country_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.country')),
                ('origin_country_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_country_id', to='base.country')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.customer')),
                ('flight_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.flight')),
            ],
            options={
                'unique_together': {('flight_id', 'customer_id')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='airline_companies',
            name='Country_Id',
        ),
        migrations.RemoveField(
            model_name='airline_companies',
            name='User_Id',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='User_Id',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='Airline_Company_Id',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='Destination_Country_Id',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='Origin_Country_Id',
        ),
        migrations.AlterUniqueTogether(
            name='tickets',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='Customer_Id',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='Flight_Id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='User_Role',
        ),
        migrations.DeleteModel(
            name='Adminstrators',
        ),
        migrations.DeleteModel(
            name='Airline_Companies',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
        migrations.DeleteModel(
            name='Flights',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
        migrations.DeleteModel(
            name='User_Roles',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.userrole'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.user'),
        ),
        migrations.AddField(
            model_name='airlinecompany',
            name='country_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.country'),
        ),
        migrations.AddField(
            model_name='airlinecompany',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.user'),
        ),
        migrations.AddField(
            model_name='adminstrator',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.user'),
        ),
    ]
